"""Expand user.name

Revision ID: 565b2585b771
Revises: 
Create Date: 2025-06-30 18:08:50.310664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '565b2585b771'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sqlmodel.sql.sqltypes.AutoString(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=40),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
